# Generated by Django 4.1 on 2022-10-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_car_slug_manufacturer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
