# Generated by Django 4.1 on 2022-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0006_alter_car_slug_alter_manufacturer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
