# Generated by Django 4.1 on 2022-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0007_alter_driver_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="slug",
        ),
    ]
