# Generated by Django 4.1 on 2022-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0008_remove_car_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="slug",
        ),
        migrations.AlterField(
            model_name="driver",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
